inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  CacheRootDirectory: 'tmp/cache'
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 3.3.0
  TargetRailsVersion: 7.0

Bundler:
  Enabled: true

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
  SupportedStyles:
    - outdent
    - indent

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundArguments:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EndAlignment:
  AutoCorrect: true

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/BigDecimalNew:
  Enabled: true # todo

# Lint/DeprecatedOpenSSLConstant:
#   Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantWithIndex:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Metrics/AbcSize:
  Enabled: false
  Max: 20 # default: 15

Metrics/BlockLength:
  Enabled: false
  Max: 100

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false # TODO
  EnforcedStyle: snake_case

Rails/CreateTableWithTimestamps:
  Enabled: true
  Exclude:
    - "db/migrate/2018*"
    - "db/migrate/2019*"
    - "db/migrate/20200*"

Rails/FindEach:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false # TODO

Rails/HasManyOrHasOneDependent:
  Enabled: false # TODO

Rails/NotNullColumn:
  Enabled: false

Rails/Output:
  Enabled: true
  Exclude:
    - "db/**/*"
    - "config/**/*"

Rails/OutputSafety:
  Enabled: false # TODO

Rails/ReversibleMigration:
  Enabled: true
  Exclude:
    - "db/migrate/2018*"
    - "db/migrate/2019*"
    - "db/migrate/20200*"

Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - "db/migrate/*"
    - "lib/tasks/**/*"

Rails/UniqueValidationWithoutIndex:
  Enabled: false # TODO

Rails/UnknownEnv:
  Enabled: false # TODO: Use something other than RAILS_ENV for sandbox/staging

Style/AccessModifierDeclarations:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - "spec/**/*"

Style/Dir:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/FloatDivision:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true # false by default
  Exclude:
    - "config/routes.rb"
    - "config/routes/*"
    - "Gemfile"
    - "spec/factories/**/*"
  IgnoreMacros: true
  AllowedMethods:
    - include
    - load
    - print
    - private
    - protected
    - public
    - puts
    - raise
    - require
    - require_relative
    # rake
    - desc
    - namespace
    - task
    # rspec
    - after
    - and
    - around
    - before
    - context
    - describe
    - include_context
    - include_example
    - include_examples
    - it
    - it_behaves_like
    - not_to
    - shared_context
    - shared_examples
    - shared_examples_for
    - specify
    - to
    - to_not
    # swagger
    - key
    - operation
    - property
    - response
    - security_definition
    - swagger_path
    - swagger_schema

Style/ModuleFunction:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

#
# Temporary disabled
#

Layout/LineLength:
  Enabled: false # TODO
  Max: 100 # default: 80

Lint/IneffectiveAccessModifier:
  Enabled: true

Lint/MissingCopEnableDirective:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
  Exclude:
    - "spec/**/*"

Naming/MemoizedInstanceVariableName:
  Enabled: false # TODO
  EnforcedStyleForLeadingUnderscores: required

Naming/PredicateName:
  Enabled: false
  Exclude:
    - "spec/**/*"

Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false
  Exclude:
    - "spec/**/*"

Style/ClassVars:
  Enabled: true
  Exclude:
    - "spec/**/*"

Style/DateTime:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: true
  Exclude:
    - "config/routes.rb"

Style/GuardClause:
  Enabled: true

Style/MixinUsage:
  Enabled: true

Style/NumericPredicate:
  Enabled: false # TODO
  Exclude:
    - "spec/**/*"

Style/SafeNavigation:
  Enabled: true

Style/StructInheritance:
  Enabled: true
  Exclude:
    - "spec/**/*"

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Layout/LineEndStringConcatenationIndentation: # (new in 1.18)
  Enabled: true
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/EmptyInPattern: # (new in 1.16)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Naming/InclusiveLanguage: # (new in 1.18)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashConversion: # (new in 1.10)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true
Style/InPatternThen: # (new in 1.16)
  Enabled: true
Style/MultilineInPatternThen: # (new in 1.16)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/QuotedSymbols: # (new in 1.16)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/StringChars: # (new in 1.12)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
Rails/ActiveRecordCallbacksOrder: # (new in 2.7)
  Enabled: true
Rails/AddColumnIndex: # (new in 2.11)
  Enabled: true
Rails/AfterCommitOverride: # (new in 2.8)
  Enabled: true
Rails/AttributeDefaultBlockValue: # (new in 2.9)
  Enabled: true
Rails/EagerEvaluationLogMessage: # (new in 2.11)
  Enabled: true
Rails/ExpandedDateRange: # (new in 2.11)
  Enabled: true
Rails/FindById: # (new in 2.7)
  Enabled: true
Rails/I18nLocaleAssignment: # (new in 2.11)
  Enabled: true
Rails/Inquiry: # (new in 2.7)
  Enabled: true
Rails/MailerName: # (new in 2.7)
  Enabled: true
Rails/MatchRoute: # (new in 2.7)
  Enabled: true
Rails/NegateInclude: # (new in 2.7)
  Enabled: true
Rails/Pluck: # (new in 2.7)
  Enabled: true
Rails/PluckInWhere: # (new in 2.7)
  Enabled: true
Rails/RenderInline: # (new in 2.7)
  Enabled: true
Rails/RenderPlainText: # (new in 2.7)
  Enabled: true
Rails/ShortI18n: # (new in 2.7)
  Enabled: true
Rails/SquishedSQLHeredocs: # (new in 2.8)
  Enabled: false
Rails/TimeZoneAssignment: # (new in 2.10)
  Enabled: true
Rails/UnusedIgnoredColumns: # (new in 2.11)
  Enabled: true
Rails/WhereEquals: # (new in 2.9)
  Enabled: true
Rails/WhereExists: # (new in 2.7)
  Enabled: true
Rails/WhereNot: # (new in 2.8)
  Enabled: true
Gemspec/RequireMFA: # new in 1.23
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true
Naming/BlockForwarding: # new in 1.24
  Enabled: false
Security/IoMethods: # new in 1.22
  Enabled: true
Style/FileRead: # new in 1.24
  Enabled: true
Style/FileWrite: # new in 1.24
  Enabled: true
Style/MapToHash: # new in 1.24
  Enabled: true
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: true
Style/OpenStructUse: # new in 1.23
  Enabled: false
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true
Style/SelectByRegexp: # new in 1.22
  Enabled: true
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true
Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true
Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true
Security/CompoundHash: # new in 1.28
  Enabled: true
Style/EmptyHeredoc: # new in 1.32
  Enabled: true
Style/EnvHome: # new in 1.29
  Enabled: true
Style/FetchEnvVar: # new in 1.28
  Enabled: true
Style/MagicCommentFormat: # new in 1.35
  Enabled: true
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true
Style/NestedFileDirname: # new in 1.26
  Enabled: true
Style/ObjectThen: # new in 1.28
  Enabled: true
Style/OperatorMethodCall: # new in 1.37
  Enabled: true
Style/RedundantEach: # new in 1.38
  Enabled: true
Style/RedundantInitialize: # new in 1.27
  Enabled: true
Style/RedundantStringEscape: # new in 1.37
  Enabled: true
Rails/ActionControllerFlashBeforeRender: # new in 2.16
  Enabled: true
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: true
Rails/ActionOrder: # new in 2.17
  Enabled: true
Rails/ActiveSupportOnLoad: # new in 2.16
  Enabled: true
Rails/CompactBlank: # new in 2.13
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: false # false positives
Rails/DotSeparatedKeys: # new in 2.15
  Enabled: true
Rails/DuplicateAssociation: # new in 2.14
  Enabled: true
Rails/DuplicateScope: # new in 2.14
  Enabled: true
Rails/DurationArithmetic: # new in 2.13
  Enabled: true
Rails/FreezeTime: # new in 2.16
  Enabled: true
Rails/I18nLazyLookup: # new in 2.14
  Enabled: true
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: false # to evaluate
Rails/IgnoredColumnsAssignment: # new in 2.17
  Enabled: true
Rails/MigrationClassName: # new in 2.14
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: false # does not work with conditional validation
Rails/RedundantTravelBack: # new in 2.12
  Enabled: true
Rails/RootJoinChain: # new in 2.13
  Enabled: true
Rails/RootPathnameMethods: # new in 2.16
  Enabled: true
Rails/RootPublicPath: # new in 2.15
  Enabled: true
Rails/StripHeredoc: # new in 2.15
  Enabled: true
Rails/ToFormattedS: # new in 2.15
  Enabled: true
Rails/ToSWithArgument: # new in 2.16
  Enabled: true
Rails/TopLevelHashWithIndifferentAccess: # new in 2.16
  Enabled: true
Rails/TransactionExitStatement: # new in 2.14
  Enabled: true
Rails/WhereMissing: # new in 2.16
  Enabled: true
Rails/WhereNotWithMultipleConditions: # new in 2.17
  Enabled: true
Performance/AncestorsInclude: # new in 1.7
  Enabled: true
Performance/BigDecimalWithNumericArgument: # new in 1.7
  Enabled: true
Performance/BlockGivenWithExplicitBlock: # new in 1.9
  Enabled: true
Performance/CollectionLiteralInLoop: # new in 1.8
  Enabled: true
Performance/ConcurrentMonotonicTime: # new in 1.12
  Enabled: true
Performance/ConstantRegexp: # new in 1.9
  Enabled: true
Performance/MapCompact: # new in 1.11
  Enabled: true
Performance/MethodObjectAsBlock: # new in 1.9
  Enabled: true
Performance/RedundantEqualityComparisonBlock: # new in 1.10
  Enabled: true
Performance/RedundantSortBlock: # new in 1.7
  Enabled: true
Performance/RedundantSplitRegexpArgument: # new in 1.10
  Enabled: true
Performance/RedundantStringChars: # new in 1.7
  Enabled: true
Performance/ReverseFirst: # new in 1.7
  Enabled: true
Performance/SortReverse: # new in 1.7
  Enabled: true
Performance/Squeeze: # new in 1.7
  Enabled: true
Performance/StringIdentifierArgument: # new in 1.13
  Enabled: true
Performance/StringInclude: # new in 1.7
  Enabled: true
Performance/Sum: # new in 1.8
  Enabled: true

AllCops:
  CacheRootDirectory: 'tmp/cache'
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/migrations/**/*'
    - 'lib/**/*'
  TargetRubyVersion: 2.7.0
  TargetRailsVersion: 5.0

Rails:
  Exclude:
    - 'app/relations/**/*'
    - 'app/domains/**/*'

Rails/SkipsModelValidations:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/201[1-9]*'
    - 'db/migrate/2020*'
    - 'db/migrate/20210[1-7]*'

Rails/CreateTableWithTimestamps:
  Enabled: false

Performance/InefficientHashSearch:
  Enabled: false
Performance/CollectionLiteralInLoop:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/RedundantInitialize:
  Enabled: false